### PR TITLE
Resolves screen tearing issues on 11" pinebook

### LINKED ISSUE #63: Screen tearing or interlacing on 11" pinebook
Simon, as requested, here is a diff of your dts which appears to be used as is in armbian, against ayufans. 

There are only three elements of importance to this gremlin, as there are quite a lot of differences:
lcd_dclk_freq
lcd_ht
lcd_vt

Changing `lcd_dclk_freq` to `<0x4d>` appears to resolve the issue of tearing/interlacing for the most part - hard to tell as I don't know if XFCE is introducing it's own issues... but the really noticeable tearing/interlacing is gone. I don't know if the other two are strictly needed, but they result in the refresh rate dropping from an increased 64 hz after the first setting is applied (from 60hz) back down the 56hz which is what ayufan's images are currently running at. 

The  `lcd_pwm_freq` that section is also different, but I'm not sure of it's effect... I suspect it's to do with the lcd brightness... maybe brightness stages? but I haven't noticed any differences in that yet, so can't say one way or the other if should also be changed.

I'll submit a PR with these three lines changed referencing this issue for your convenience ;)

[diff.txt](https://github.com/longsleep/build-pine64-image/files/1040265/diff.txt)

### PR DESCRIPTION
**Pull request by pfeerick**
Resolves #63

### CODE REVIEW

**Comment by ayufan** [comment]
Great! It seems that this is parameters from sys_config.fex: https://github.com/ayufan-pine64/boot-tools/blob/master/blobs/sys_config_pine64-pinebook.fex#L549 !

**Comment by pfeerick** [comment]
By that, do you mean that's the reason it's set to that value? I'm a complete novice when it comes to DTS. I though that FEX wasn't applicable anymore now that we have the DTSs.

**Comment by ayufan** [comment]
I'm using FEX as currently it is simpler to merge kernel's dts with user configuration of the board.

**Comment by pfeerick** [comment]
Ah ha... I gotcha now... I think! ;-) Explains why I didn't see any DTS files around your repo and the DTB blobs instead. Thanks! Can you have a look at https://forum.pine64.org/showthread.php?tid=4564 when you get a chance and see if you can give me any pointers?

**Pull request merged**
