### PR TITLE
add OneWire into DTS

### PR DESCRIPTION
**Pull request by martinayotte**
As requested, here is the W1 DTS that allows to connect devices such DS18B20 if EndUser enable it in DTS by changing "disabled" with "okay".

### CODE REVIEW

**Comment by longsleep** [comment]
I keep this as PR for now as the Kernel does not have the w1 driver enabled. I might change this in the future and then merge. 

If anyone wants to use W1, use the DTS changes from this PR and enable CONFIG_W1 in your Kernel build.

**Comment by martinayotte** [comment]
Hi Simon,

Do you wish that I had the config changes in this PR too ?

EDIT : opps ! I forgot, the changes need to be done on the other repo.

**Comment by longsleep** [comment]
Thanks Martin but that's not necessary - i think everyone who needs it can figure it out.

**Comment by martinayotte** [comment]
Hi Simon, 

You can see that I've done new fix unrelated with the previous, but unfortunately, when a PR is already opened, new commits are coming into the same PR since previous wasn't merged.

The description of the new fix is explain here : 
http://forum.pine64.org/showthread.php?tid=1297&pid=15958#pid15958

**Comment by longsleep** [comment]
Thanks - I cherry picked 8a0440a and you can rebase and force push to get this PR clean again. Also you can always also create another branch on top of master and submit a new PR for this branch to avoid getting things mixed up.

**Comment by martinayotte** [comment]
Rebase done !

**Pull request merged**
